Repository itsnporg/Basic-Programs, pull requests merged in 2022-10, with the labels that each got.

#18 Added a simple Fibonacci series generator
  Python/generate_fib.py
Labels: hacktoberfest-accepted

#13 Python program1 1
  Python/screenshot.py
Labels: hacktoberfest-accepted

#10 Two-sum problem in c++
  C++/2sum.cpp
Labels: hacktoberfest-accepted

#19 habit-tracker
  Python/habittracker.py
Labels: hacktoberfest-accepted

#12 Create sort-vectors
  Rust/sort-vectors
Labels: hacktoberfest-accepted

#21 add golang script
  Golang/http_serve.go
Labels: hacktoberfest-accepted

#28 Audio Classification program ML.js
  JavaScript/ML.js
Labels: hacktoberfest-accepted

#31 Newton Raphson Method calculator
  Python/newton_raphson.py
Labels: hacktoberfest-accepted

#30 Shutdown.py
  Python/shutdown.py
Labels: hacktoberfest-accepted

#33 Added Repository thumbnail
  README.md
Labels: hacktoberfest-accepted

#29 Create concatenate_strings.cpp
  C++/concatenate_strings.cpp
Labels: hacktoberfest-accepted

#34 Bubble sort Algorithm bubblesort.c
  C/bubbleSort.c
  C/linearQueue.c
Labels: hacktoberfest-accepted

#38 added C programs
  C/insertion_sort.c
  C/leap_year.c
  C/linear_search.c
  C/matrix_calculator.c
  C/matrix_viewer.c
  C/max_min_array.c
  C/merge_sort_full.c
Labels: hacktoberfest-accepted

#36 Added Web page cloner in python/webpage_cloner.py
  Python/webpage_cloner.py
Labels: hacktoberfest-accepted

#35 Create oddoreven.py
  Python/oddoreven.py
Labels: hacktoberfest-accepted

#40 Added Qr code generator
  Python/qrcode_generator.py
Labels: hacktoberfest-accepted

#41 feat: add fizzbuzz program in Rust
  Rust/fizzbuzz.rs
Labels: hacktoberfest-accepted

#42 Binary search
  Java/BinarySearch.java
Labels: hacktoberfest-accepted

#39 Greatest of three number
  C/greatestofthree.C
Labels: hacktoberfest-accepted

#44 instagram dp downloader
  Python/insta_prof.py
Labels: hacktoberfest-accepted

#46 Added the new fibonacci program using recursion in C
  C/fibonacci.c
Labels: hacktoberfest-accepted

#43 Kushal subedi
  C/Uppercase_to_lowercase.c
  C/reversestring.c
Labels: hacktoberfest-accepted

#50 Added validate_password_strength.py
  Python/validate_password_strength.py
Labels: hacktoberfest-accepted

#47 Create prime.py
  Python/prime.py
Labels: hacktoberfest-accepted

#54 chessboard program
  JavaScript/ChessBoard.js
Labels: hacktoberfest-accepted

#49 love calculator
  Python/love_calc.py
Labels: hacktoberfest-accepted

#52 added c builtin string function
  C/simple_interest.c
  C/square_finder.c
  C/strcat().c
  C/strcmp().c
  C/strcpy().c
  C/strlen().c
Labels: hacktoberfest-accepted

#15 Create prison_break.py
  prison_break.py
Labels: hacktoberfest-accepted

#23 Create Battery_percentage.py
  Python/Battery_percentage.py
Labels: hacktoberfest-accepted

#24 Create GUI_dice_roll.py
  Python/GUI_dice_roll.py
Labels: hacktoberfest-accepted

#53 Added restaurant_bill system
  C/restaurant_bill.c
Labels: hacktoberfest-accepted

#56 tic tac toe
  C/tt.c
  Python/tt.py
Labels: hacktoberfest-accepted

#57 Bean Counting Program
  JavaScript/BeanCounting.js
Labels: hacktoberfest-accepted

#58 Create palindrome_number.py
  Python/palindrome_number.py
Labels: hacktoberfest-accepted

#55 complex number arithmetic
  C++/Bisection.cpp
  C/Complex number.c
Labels: hacktoberfest-accepted

#59 Reverse Linked List
  Java/ReverseLinkedList.java
Labels: hacktoberfest-accepted

#60 Add javascript a linear search
  JavaScript/linearSearch.js
Labels: hacktoberfest-accepted

#61 Add Tic tac toe in CPP
  C++/calculator.cpp
  C++/menu.cpp
  C++/tic-tac-toe.cpp
Labels: hacktoberfest-accepted

#65 Python Sorting Algorithms
  Python/bubble_sort.py
  Python/insertion_sort.py
  Python/selection_sort.py
Labels: hacktoberfest-accepted

#66 Added Codes for LCS and LPS of Dynamic Programming in C++ Folder
  C++/Longest_Common_Subsequence.cpp
  C++/Longest_Palindromic_Substring.cpp
Labels: hacktoberfest-accepted

#67 Added SuperHero.js
  JavaScript/SuperHero.js
Labels: hacktoberfest-accepted

#68 Kushal subedi
  .gitignore
  C/Uppercase_to_lowercase.c
  Python/newton_raphson.py
  Python/oopConcepts/class.py
  Python/oopConcepts/classWithmethods.py
Labels: hacktoberfest-accepted

#69 added sorting algorithms code in java
  Java/BubbleSort.java
  Java/InsertionSort.java
Labels: hacktoberfest-accepted

#70 Added Password Generator
  Java/PasswordGenerator.java
Labels: hacktoberfest-accepted

#71 Check Local IP Address with Java
  Java/IPAddress.java
Labels: hacktoberfest-accepted

#74 Create multiplication_table.py
  Python/multiplication_table.py
Labels: hacktoberfest-accepted

#75 Added a Find a peak element in a matrix program
  C++/Find_A_Peak_Element_In_2D_Matrix.cpp
Labels: hacktoberfest-accepted

#79 Create ritikakr_digitalclock.py
  ritikakr_digitalclock.py
Labels: hacktoberfest-accepted

#76 Added Merge Sort Algorithm using Recursion
  C++/MergeSort.cpp
Labels: hacktoberfest-accepted

#77 Create countdigits.py
  Python/countdigits.py
Labels: hacktoberfest-accepted

#82 Lagranges Interpolation v2
  C++/Lagrange_s Interpolation.cpp
Labels: hacktoberfest-accepted

#81 Create factorial.groovy
  Groovy/factorial.groovy
Labels: hacktoberfest-accepted

#72 update c and c++ code
  C++/Linked_list_cycle_2.cpp
  C++/Remove_Nth_Node_From_End_of_List.cpp
  C++/add_two_numbers.cpp
  C/doubly_linked_list.c
Labels: hacktoberfest-accepted

#89 doublyLinkedList added
  Python/doublyLinkedList.py
Labels: hacktoberfest-accepted

#91 Create Time_difference.py
  Python/Time_difference.py
Labels: hacktoberfest-accepted

#88 Trapezoidal Rule
  C++/Trapezoidal Rule (function).cpp
Labels: hacktoberfest-accepted, hacktoberfest

#117 added leap year check using python
  Python/leap_year_checker.py
Labels: hacktoberfest-accepted, hacktoberfest

#123 Amazon price tracker
  Python/amazonpricetracker.py
Labels: hacktoberfest-accepted, hacktoberfest

#130 Add bank-management to python projects
  Python/bank-management/bank.py
  Python/bank-management/main.py
Labels: hacktoberfest-accepted, hacktoberfest

#129 c programm that validate passwords
  C/Password validator.c
Labels: hacktoberfest-accepted, hacktoberfest

#118 Guessing game vs CPU gui based
  Java/Guessing Game in JAVA GUI Based/Guessing_Game_Human_vs_CPU.java
  Java/Guessing Game in JAVA GUI Based/ScreenCapture_06-01-2021 21.58.10.xesc
  Java/Guessing Game in JAVA GUI Based/Screenshot (1999).png
  Java/Guessing Game in JAVA GUI Based/Screenshot (2000).png
  Java/Guessing Game in JAVA GUI Based/Screenshot (2001).png
Labels: hacktoberfest-accepted, hacktoberfest

#135 add dice game
  JavaScript/diceGame.js
Labels: hacktoberfest-accepted, hacktoberfest

#134 async and await in javascript
  JavaScript/Learn_async_await.js
Labels: hacktoberfest-accepted, hacktoberfest

#132 simple pattern matching using re
  Python/flask_api.py
  Python/hamroPatro.py
  Python/regex.py
Labels: hacktoberfest-accepted, hacktoberfest

#121 Longest Special Subsequence
  C++/Longest-Special-Subsequence.cpp.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#120 Mass Email Sender App
  Python/email.py
Labels: hacktoberfest-accepted

#136 Pacman game in Python
  Python/Pacman.py
Labels: hacktoberfest-accepted, hacktoberfest

#143 Add Binary Tree Preorder Traversal
  Java/BinaryTreePreorderTraversal.java
Labels: hacktoberfest-accepted, hacktoberfest

#149 added 2 python files inside python dir which were outside before
  Python/prison_break.py
  Python/ritikakr_digitalclock.py
Labels: changes-requested

#146 Add Binary Tree PostOrder Traversal
  Java/BinaryTreePostorderTraversal.java
Labels: hacktoberfest-accepted

#133 Create db_connect.php
  PHP/db_connect.php
Labels: hacktoberfest-accepted

#116 Add howto for Clojure
  Clojure/.gitignore
  Clojure/clojure-how-to/.DS_Store
  Clojure/clojure-how-to/.idea/$CACHE_FILE$
  Clojure/clojure-how-to/.idea/$PRODUCT_WORKSPACE_FILE$
  Clojure/clojure-how-to/.idea/.gitignore
  Clojure/clojure-how-to/.idea/ClojureProjectResolveSettings.xml
  Clojure/clojure-how-to/.idea/codeStyles
  Clojure/clojure-how-to/.idea/compiler.xml
  Clojure/clojure-how-to/.idea/dbnavigator.xml
  Clojure/clojure-how-to/.idea/libraries/Leiningen__clojure_complete_0_2_5.xml
  Clojure/clojure-how-to/.idea/libraries/Leiningen__nrepl_0_6_0.xml
  Clojure/clojure-how-to/.idea/libraries/Leiningen__org_clojure_clojure_1_10_0.xml
  Clojure/clojure-how-to/.idea/libraries/Leiningen__org_clojure_core_specs_alpha_0_2_44.xml
  Clojure/clojure-how-to/.idea/libraries/Leiningen__org_clojure_spec_alpha_0_2_176.xml
  Clojure/clojure-how-to/.idea/misc.xml
  Clojure/clojure-how-to/.idea/modules.xml
  Clojure/clojure-how-to/.idea/vcs.xml
  Clojure/clojure-how-to/.nrepl-port
  Clojure/clojure-how-to/CHANGELOG.md
  Clojure/clojure-how-to/LICENSE
  Clojure/clojure-how-to/README.md
  Clojure/clojure-how-to/app.iml
  Clojure/clojure-how-to/doc/intro.md
  Clojure/clojure-how-to/project.clj
  Clojure/clojure-how-to/src/.DS_Store
  Clojure/clojure-how-to/src/app/core.clj
  Clojure/clojure-how-to/target/classes/META-INF/maven/app/app/pom.properties
  Clojure/clojure-how-to/target/repl-port
  Clojure/clojure-how-to/target/stale/leiningen.core.classpath.extract-native-dependencies
  Clojure/clojure-how-to/test/app/core_test.clj
Labels: hacktoberfest-accepted

#168 added a script to download YouTube videos
  Python/yt_download.py
Labels: hacktoberfest-accepted
